//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALIQUOT_FORMULATION
    {
        public long PARENT_ALIQUOT_ID { get; set; }
        public long CHILD_ALIQUOT_ID { get; set; }
        public Nullable<decimal> AMOUNT_USED { get; set; }
        public Nullable<decimal> DILUTION_FACTOR { get; set; }
        public Nullable<long> UNIT_ID { get; set; }
    
        public virtual ALIQUOT CHILDREN { get; set; }
        public virtual ALIQUOT PARENT { get; set; }
    }
}
