//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALIQUOT
    {
        public ALIQUOT()
        {
            this.TESTs = new HashSet<TEST>();
            this.ALIQ_FORMULATION_CHILD = new HashSet<ALIQUOT_FORMULATION>();
            this.ALIQ_FORMULATION_PARENT = new HashSet<ALIQUOT_FORMULATION>();
            this.U_ALL_BARCODE_SCAN_USER = new HashSet<U_ALL_BARCODE_SCAN_USER>();
        }
    
        public long ALIQUOT_ID { get; set; }
        public Nullable<long> SAMPLE_ID { get; set; }
        public Nullable<long> OPERATOR_ID { get; set; }
        public Nullable<long> LOCATION_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string MATRIX_TYPE { get; set; }
        public string CONCLUSION { get; set; }
        public string CONDITION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DATE_RESULTS_REQUIRED { get; set; }
        public Nullable<System.DateTime> EXPECTED_ON { get; set; }
        public Nullable<System.DateTime> EXPIRES_ON { get; set; }
        public Nullable<long> PLATE_ALIQUOT_TYPE { get; set; }
        public string ARCHIVED_CHILD_COMPLETE { get; set; }
        public Nullable<long> CONTAINER_TYPE_ID { get; set; }
        public Nullable<long> ALIQUOT_TEMPLATE_ID { get; set; }
        public Nullable<long> WORKFLOW_NODE_ID { get; set; }
        public Nullable<int> USAGE_COUNT { get; set; }
        public Nullable<long> STOCK_TEMPLATE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> COMPLETED_ON { get; set; }
        public Nullable<System.DateTime> AUTHORISED_ON { get; set; }
        public string EVENTS { get; set; }
        public Nullable<long> UNIT_ID { get; set; }
        public string NEEDS_REVIEW { get; set; }
        public Nullable<long> INSPECTION_PLAN_ID { get; set; }
        public Nullable<long> RECEIVED_BY { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string REPORTED { get; set; }
        public string HAS_NOTES { get; set; }
        public string HAS_AUDITS { get; set; }
        public string ALIQUOT_TYPE { get; set; }
        public string STORAGE { get; set; }
        public string EXTERNAL_REFERENCE { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<long> COMPLETED_BY { get; set; }
        public Nullable<long> AUTHORISED_BY { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<long> CHEMICAL_ID { get; set; }
        public Nullable<long> STOCK_TYPE_ID { get; set; }
        public string GRADE { get; set; }
        public string BATCH_NUMBER { get; set; }
        public Nullable<decimal> PURITY { get; set; }
        public Nullable<long> PLATE_ID { get; set; }
        public Nullable<int> PLATE_ORDER { get; set; }
        public Nullable<int> PLATE_ROW { get; set; }
        public Nullable<int> PLATE_COLUMN { get; set; }
        public Nullable<long> PLATE_EDITOR_ID { get; set; }
    
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual OPERATOR OPERATOR1 { get; set; }
        public virtual OPERATOR OPERATOR2 { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual INSPECTION_PLAN INSPECTION_PLAN { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual OPERATOR OPERATOR3 { get; set; }
        public virtual OPERATOR OPERATOR4 { get; set; }
        public virtual SAMPLE SAMPLE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual ALIQUOT_USER ALIQUOT_USER { get; set; }
        public virtual WORKFLOW_NODE WORKFLOW_NODE { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
        public virtual ICollection<ALIQUOT_FORMULATION> ALIQ_FORMULATION_CHILD { get; set; }
        public virtual ICollection<ALIQUOT_FORMULATION> ALIQ_FORMULATION_PARENT { get; set; }
        public virtual ICollection<U_ALL_BARCODE_SCAN_USER> U_ALL_BARCODE_SCAN_USER { get; set; }
    }
}
