//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_USER
    {
        public long CLIENT_ID { get; set; }
        public Nullable<System.DateTime> U_DATE_OF_BIRTH { get; set; }
        public string U_FIRST_NAME { get; set; }
        public string U_LAST_NAME { get; set; }
        public string U_GENDER { get; set; }
        public string U_ID_CODE { get; set; }
        public Nullable<decimal> U_AGE { get; set; }
        public string U_PHONE { get; set; }
        public string U_PASSPORT { get; set; }
        public string U_PHON_2 { get; set; }
        public string U_VISIT_1 { get; set; }
        public string U_VISIT_2 { get; set; }
        public string U_FATHER_NAME { get; set; }
        public string U_R_R_CASE { get; set; }
        public string U_PREV_LAST_NAME { get; set; }
        public string U_SEND_CODED_LETTER { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
