//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.CLIENT1 = new HashSet<CLIENT>();
            this.SDG_USER = new HashSet<SDG_USER>();
            this.SAMPLEs = new HashSet<SAMPLE>();
            this.U_SAMPLE_MSG_USER = new HashSet<U_SAMPLE_MSG_USER>();
        }
    
        public long CLIENT_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string BAD_DEBT { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<decimal> CLIENT_DISCOUNT { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
        public string CLIENT_TYPE { get; set; }
        public string CLIENT_CODE { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<CLIENT> CLIENT1 { get; set; }
        public virtual CLIENT CLIENT2 { get; set; }
        public virtual CLIENT_USER CLIENT_USER { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER { get; set; }
        public virtual ICollection<SAMPLE> SAMPLEs { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_USER> U_SAMPLE_MSG_USER { get; set; }
    }
}
