//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYTOLOGY_WORKLIST
    {
        public long SDG_ID { get; set; }
        public string SDG_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> U_PATHOLOG { get; set; }
        public Nullable<System.DateTime> CONTAINER_RECEIVE { get; set; }
        public string PARTS_NAME { get; set; }
        public Nullable<decimal> PRIORITY_NUM { get; set; }
        public string PRIORITY { get; set; }
    }
}
