//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_REQ_WORKLIST_ERR
    {
        public long SDG_ID { get; set; }
        public string ID { get; set; }
        public Nullable<long> SDG_PATHOLAB_NUMBER { get; set; }
        public string SAMPLE_PATHOLAB_NUMBER { get; set; }
        public string ALIQUOT_PATHOLAB_NUMBER { get; set; }
        public string PRIORITY { get; set; }
        public Nullable<decimal> SDG_CREATED_ON { get; set; }
        public Nullable<System.DateTime> BLOCK_NUMBER { get; set; }
        public string SLIDE_NUMBER { get; set; }
        public string PATHOLOG_NAME { get; set; }
        public string PATHOLOG_MACRO { get; set; }
        public Nullable<System.DateTime> PATHOLOG_MACRO_TIME { get; set; }
        public Nullable<System.DateTime> REQUEST_CREATED_ON { get; set; }
        public string REQUEST_NAME { get; set; }
        public string REQUEST_ENTITY_TYPE { get; set; }
        public string REQUEST_DETAILS { get; set; }
        public string REQUEST_STATUS { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string REQUEST_REMARKS { get; set; }
        public string CUTTING_LABORANT { get; set; }
        public string SEDIMENTATION_LABORANT { get; set; }
    }
}
