//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRA_MATERIAL
    {
        public long SDG_ID { get; set; }
        public long REQ_ID { get; set; }
        public string SDG_PATHOLAB_NUMBER { get; set; }
        public string PRIORITY { get; set; }
        public string U_REQUEST_DETAILS { get; set; }
        public string PATHOLOG_NAME { get; set; }
        public Nullable<System.DateTime> REQ_CREATED_ON { get; set; }
        public string SDG_NAME { get; set; }
        public string SAMPLE_NAME { get; set; }
        public string U_SLIDE_NAME { get; set; }
        public string REQUEST_ENTITY_TYPE { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string REQUEST_REMARKS { get; set; }
        public string PATHOLOG_MACRO { get; set; }
        public Nullable<System.DateTime> PATHOLOG_MACRO_TIME { get; set; }
        public Nullable<System.DateTime> CONTAINERRECEIVEDON { get; set; }
        public string REQUEST_STATUS { get; set; }
        public Nullable<decimal> PRIORITY_NUM { get; set; }
    }
}
