//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRA_CELL_BLOCK
    {
        public long SDG_ID { get; set; }
        public string ALIQUOT_NAME { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string U_PATHOLAB_NUMBER { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public long EX_REQ_DATA_ID { get; set; }
        public string SAMP_NAME { get; set; }
        public string EX_REQ_STATUS { get; set; }
        public Nullable<System.DateTime> FIRST_MACRO_TIME { get; set; }
    }
}
