//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTION_ENTRY
    {
        public long INSPECTION_PLAN_ID { get; set; }
        public decimal INSPECTION_ORDER { get; set; }
        public Nullable<long> ROLE_ID { get; set; }
        public string PROPAGATE_UP { get; set; }
        public string SEQUENTIAL { get; set; }
        public string IN_REVIEW { get; set; }
    
        public virtual LIMS_ROLE LIMS_ROLE { get; set; }
        public virtual INSPECTION_PLAN INSPECTION_PLAN { get; set; }
    }
}
