//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTION_LOG
    {
        public long INSPECTION_LOG_ID { get; set; }
        public Nullable<long> ROLE_ID { get; set; }
        public Nullable<long> OPERATOR_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<long> TABLE_KEY { get; set; }
        public string INSPECTION_TYPE { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
    
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual LIMS_ROLE LIMS_ROLE { get; set; }
    }
}
