//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMS_GROUP
    {
        public LIMS_GROUP()
        {
            this.ALIQUOTs = new HashSet<ALIQUOT>();
            this.CLIENTs = new HashSet<CLIENT>();
            this.INSPECTION_PLAN = new HashSet<INSPECTION_PLAN>();
            this.U_CLINIC = new HashSet<U_CLINIC>();
            this.U_CONTAINER = new HashSet<U_CONTAINER>();
            this.U_CUSTOMER = new HashSet<U_CUSTOMER>();
            this.U_DEBIT = new HashSet<U_DEBIT>();
            this.U_ORDER = new HashSet<U_ORDER>();
            this.U_PARTS = new HashSet<U_PARTS>();
            this.U_PRICE_LIST = new HashSet<U_PRICE_LIST>();
            this.U_SPECIAL_INSPECTION = new HashSet<U_SPECIAL_INSPECTION>();
            this.U_START_SCREEN = new HashSet<U_START_SCREEN>();
            this.U_WREPORT = new HashSet<U_WREPORT>();
            this.U_WREPORT_QUERY = new HashSet<U_WREPORT_QUERY>();
            this.LOCATIONs = new HashSet<LOCATION>();
            this.OPERATOR_GROUP = new HashSet<OPERATOR_GROUP>();
            this.PHRASE_HEADER = new HashSet<PHRASE_HEADER>();
            this.SAMPLEs = new HashSet<SAMPLE>();
            this.SDGs = new HashSet<SDG>();
            this.SUPPLIERs = new HashSet<SUPPLIER>();
            this.TESTs = new HashSet<TEST>();
            this.WORKFLOWs = new HashSet<WORKFLOW>();
            this.WORKSTATIONs = new HashSet<WORKSTATION>();
            this.U_NORGAN = new HashSet<U_NORGAN>();
            this.U_WRDESTINATION = new HashSet<U_WRDESTINATION>();
            this.U_CRYSTAL_REPORT = new HashSet<U_CRYSTAL_REPORT>();
            this.U_REPORT_PARAMS = new HashSet<U_REPORT_PARAMS>();
            this.U_LABORANT_WORK = new HashSet<U_LABORANT_WORK>();
            this.U_ALL_BARCODE_SCAN = new HashSet<U_ALL_BARCODE_SCAN>();
            this.U_SDG_ATTACHMENT = new HashSet<U_SDG_ATTACHMENT>();
            this.U_EXTRA_REQUEST_DATA = new HashSet<U_EXTRA_REQUEST_DATA>();
            this.U_EXTRA_REQUEST = new HashSet<U_EXTRA_REQUEST>();
            this.U_MORE_ACTION = new HashSet<U_MORE_ACTION>();
            this.U_CONTAINER_MSG = new HashSet<U_CONTAINER_MSG>();
            this.U_CONTAINER_MSG_ROW = new HashSet<U_CONTAINER_MSG_ROW>();
            this.U_SAMPLE_MSG = new HashSet<U_SAMPLE_MSG>();
            this.U_SAMPLE_MSG_ROW = new HashSet<U_SAMPLE_MSG_ROW>();
            this.U_ASSUTA_CUSTOMER = new HashSet<U_ASSUTA_CUSTOMER>();
            this.U_REQUEST_REMARK = new HashSet<U_REQUEST_REMARK>();
            this.U_NEW_RE_DESC = new HashSet<U_NEW_RE_DESC>();
            this.RESULT_TEMPLATE = new HashSet<RESULT_TEMPLATE>();
            this.U_CYTO_PRINT_CONTROL = new HashSet<U_CYTO_PRINT_CONTROL>();
        }
    
        public long GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION_STATUS { get; set; }
        public string SYSTEM_DATA { get; set; }
    
        public virtual ICollection<ALIQUOT> ALIQUOTs { get; set; }
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        public virtual ICollection<INSPECTION_PLAN> INSPECTION_PLAN { get; set; }
        public virtual ICollection<U_CLINIC> U_CLINIC { get; set; }
        public virtual ICollection<U_CONTAINER> U_CONTAINER { get; set; }
        public virtual ICollection<U_CUSTOMER> U_CUSTOMER { get; set; }
        public virtual ICollection<U_DEBIT> U_DEBIT { get; set; }
        public virtual ICollection<U_ORDER> U_ORDER { get; set; }
        public virtual ICollection<U_PARTS> U_PARTS { get; set; }
        public virtual ICollection<U_PRICE_LIST> U_PRICE_LIST { get; set; }
        public virtual ICollection<U_SPECIAL_INSPECTION> U_SPECIAL_INSPECTION { get; set; }
        public virtual ICollection<U_START_SCREEN> U_START_SCREEN { get; set; }
        public virtual ICollection<U_WREPORT> U_WREPORT { get; set; }
        public virtual ICollection<U_WREPORT_QUERY> U_WREPORT_QUERY { get; set; }
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        public virtual ICollection<OPERATOR_GROUP> OPERATOR_GROUP { get; set; }
        public virtual ICollection<PHRASE_HEADER> PHRASE_HEADER { get; set; }
        public virtual ICollection<SAMPLE> SAMPLEs { get; set; }
        public virtual ICollection<SDG> SDGs { get; set; }
        public virtual ICollection<SUPPLIER> SUPPLIERs { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
        public virtual ICollection<WORKFLOW> WORKFLOWs { get; set; }
        public virtual ICollection<WORKSTATION> WORKSTATIONs { get; set; }
        public virtual ICollection<U_NORGAN> U_NORGAN { get; set; }
        public virtual ICollection<U_WRDESTINATION> U_WRDESTINATION { get; set; }
        public virtual ICollection<U_CRYSTAL_REPORT> U_CRYSTAL_REPORT { get; set; }
        public virtual ICollection<U_REPORT_PARAMS> U_REPORT_PARAMS { get; set; }
        public virtual ICollection<U_LABORANT_WORK> U_LABORANT_WORK { get; set; }
        public virtual ICollection<U_ALL_BARCODE_SCAN> U_ALL_BARCODE_SCAN { get; set; }
        public virtual ICollection<U_SDG_ATTACHMENT> U_SDG_ATTACHMENT { get; set; }
        public virtual ICollection<U_EXTRA_REQUEST_DATA> U_EXTRA_REQUEST_DATA { get; set; }
        public virtual ICollection<U_EXTRA_REQUEST> U_EXTRA_REQUEST { get; set; }
        public virtual ICollection<U_MORE_ACTION> U_MORE_ACTION { get; set; }
        public virtual ICollection<U_CONTAINER_MSG> U_CONTAINER_MSG { get; set; }
        public virtual ICollection<U_CONTAINER_MSG_ROW> U_CONTAINER_MSG_ROW { get; set; }
        public virtual ICollection<U_SAMPLE_MSG> U_SAMPLE_MSG { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_ROW> U_SAMPLE_MSG_ROW { get; set; }
        public virtual ICollection<U_ASSUTA_CUSTOMER> U_ASSUTA_CUSTOMER { get; set; }
        public virtual ICollection<U_REQUEST_REMARK> U_REQUEST_REMARK { get; set; }
        public virtual ICollection<U_NEW_RE_DESC> U_NEW_RE_DESC { get; set; }
        public virtual ICollection<RESULT_TEMPLATE> RESULT_TEMPLATE { get; set; }
        public virtual ICollection<U_CYTO_PRINT_CONTROL> U_CYTO_PRINT_CONTROL { get; set; }
    }
}
