//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMS_ROLE
    {
        public LIMS_ROLE()
        {
            this.INSPECTION_ENTRY = new HashSet<INSPECTION_ENTRY>();
            this.INSPECTION_LOG = new HashSet<INSPECTION_LOG>();
            this.U_SPECIAL_INSPECTION_USER = new HashSet<U_SPECIAL_INSPECTION_USER>();
            this.OPERATORs = new HashSet<OPERATOR>();
            this.OPERATORs1 = new HashSet<OPERATOR>();
        }
    
        public long ROLE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<INSPECTION_ENTRY> INSPECTION_ENTRY { get; set; }
        public virtual ICollection<INSPECTION_LOG> INSPECTION_LOG { get; set; }
        public virtual ICollection<U_SPECIAL_INSPECTION_USER> U_SPECIAL_INSPECTION_USER { get; set; }
        public virtual ICollection<OPERATOR> OPERATORs { get; set; }
        public virtual ICollection<OPERATOR> OPERATORs1 { get; set; }
    }
}
