//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.ALIQUOTs = new HashSet<ALIQUOT>();
            this.LOCATION1 = new HashSet<LOCATION>();
            this.LOCATION11 = new HashSet<LOCATION>();
            this.SAMPLEs = new HashSet<SAMPLE>();
            this.TESTs = new HashSet<TEST>();
            this.WORKSTATIONs = new HashSet<WORKSTATION>();
        }
    
        public long LOCATION_ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string GRID_REFERENCE { get; set; }
        public string ELEVATION { get; set; }
        public string CAN_STORE_ITEMS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> LOCATION_TYPE_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual ICollection<ALIQUOT> ALIQUOTs { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<LOCATION> LOCATION1 { get; set; }
        public virtual LOCATION LOCATION2 { get; set; }
        public virtual ICollection<LOCATION> LOCATION11 { get; set; }
        public virtual LOCATION LOCATION3 { get; set; }
        public virtual LOCATION_USER LOCATION_USER { get; set; }
        public virtual ICollection<SAMPLE> SAMPLEs { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
        public virtual ICollection<WORKSTATION> WORKSTATIONs { get; set; }
    }
}
