//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADDRESS> ADDRESS { get; set; }
        public DbSet<ALIQUOT> ALIQUOT { get; set; }
        public DbSet<ALIQUOT_USER> ALIQUOT_USER { get; set; }
        public DbSet<CLIENT> CLIENTs { get; set; }
        public DbSet<CLIENT_USER> CLIENT_USER { get; set; }
        public DbSet<INSPECTION_ENTRY> INSPECTION_ENTRY { get; set; }
        public DbSet<INSPECTION_LOG> INSPECTION_LOG { get; set; }
        public DbSet<INSPECTION_PLAN> INSPECTION_PLAN { get; set; }
        public DbSet<LIMS_GROUP> LIMS_GROUP { get; set; }
        public DbSet<LIMS_ROLE> LIMS_ROLE { get; set; }
        public DbSet<LOCATION> LOCATIONs { get; set; }
        public DbSet<LOCATION_USER> LOCATION_USER { get; set; }
        public DbSet<OPERATOR> OPERATORs { get; set; }
        public DbSet<OPERATOR_GROUP> OPERATOR_GROUP { get; set; }
        public DbSet<PHRASE_ENTRY> PHRASE_ENTRY { get; set; }
        public DbSet<PHRASE_HEADER> PHRASE_HEADER { get; set; }
        public DbSet<RESULT> RESULTs { get; set; }
        public DbSet<SAMPLE> SAMPLEs { get; set; }
        public DbSet<SAMPLE_USER> SAMPLE_USER { get; set; }
        public DbSet<SDG> SDGs { get; set; }
        public DbSet<SDG_LOG> SDG_LOG { get; set; }
        public DbSet<SDG_USER> SDG_USER { get; set; }
        public DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public DbSet<SUPPLIER_USER> SUPPLIER_USER { get; set; }
        public DbSet<TEST> TESTs { get; set; }
        public DbSet<TEST_USER> TEST_USER { get; set; }
        public DbSet<U_CLINIC> U_CLINIC { get; set; }
        public DbSet<U_CLINIC_USER> U_CLINIC_USER { get; set; }
        public DbSet<U_CONTAINER> U_CONTAINER { get; set; }
        public DbSet<U_CONTAINER_USER> U_CONTAINER_USER { get; set; }
        public DbSet<U_CUSTOMER> U_CUSTOMER { get; set; }
        public DbSet<U_CUSTOMER_USER> U_CUSTOMER_USER { get; set; }
        public DbSet<U_DEBIT> U_DEBIT { get; set; }
        public DbSet<U_DEBIT_USER> U_DEBIT_USER { get; set; }
        public DbSet<U_ORDER> U_ORDER { get; set; }
        public DbSet<U_ORDER_USER> U_ORDER_USER { get; set; }
        public DbSet<U_PARTS> U_PARTS { get; set; }
        public DbSet<U_PARTS_USER> U_PARTS_USER { get; set; }
        public DbSet<U_PRICE_LIST> U_PRICE_LIST { get; set; }
        public DbSet<U_PRICE_LIST_USER> U_PRICE_LIST_USER { get; set; }
        public DbSet<U_SPECIAL_INSPECTION> U_SPECIAL_INSPECTION { get; set; }
        public DbSet<U_SPECIAL_INSPECTION_USER> U_SPECIAL_INSPECTION_USER { get; set; }
        public DbSet<U_START_SCREEN> U_START_SCREEN { get; set; }
        public DbSet<U_START_SCREEN_USER> U_START_SCREEN_USER { get; set; }
        public DbSet<U_WREPORT> U_WREPORT { get; set; }
        public DbSet<U_WREPORT_QUERY> U_WREPORT_QUERY { get; set; }
        public DbSet<U_WREPORT_QUERY_USER> U_WREPORT_QUERY_USER { get; set; }
        public DbSet<U_WREPORT_USER> U_WREPORT_USER { get; set; }
        public DbSet<WORKFLOW> WORKFLOWs { get; set; }
        public DbSet<WORKFLOW_NODE> WORKFLOW_NODE { get; set; }
        public DbSet<WORKFLOW_USER> WORKFLOW_USER { get; set; }
        public DbSet<ALIQUOT_FORMULATION> ALIQUOT_FORMULATION { get; set; }
        public DbSet<WORKSTATION> WORKSTATIONs { get; set; }
        public DbSet<U_NORGAN> U_NORGAN { get; set; }
        public DbSet<U_WRDESTINATION> U_WRDESTINATION { get; set; }
        public DbSet<U_WRDESTINATION_USER> U_WRDESTINATION_USER { get; set; }
        public DbSet<U_NORGAN_USER> U_NORGAN_USER { get; set; }
        public DbSet<U_CRYSTAL_REPORT> U_CRYSTAL_REPORT { get; set; }
        public DbSet<U_CRYSTAL_REPORT_USER> U_CRYSTAL_REPORT_USER { get; set; }
        public DbSet<U_REPORT_PARAMS> U_REPORT_PARAMS { get; set; }
        public DbSet<U_REPORT_PARAMS_USER> U_REPORT_PARAMS_USER { get; set; }
        public DbSet<SCHEMA_TABLE> SCHEMA_TABLE { get; set; }
        public DbSet<U_LABORANT_WORK> U_LABORANT_WORK { get; set; }
        public DbSet<U_LABORANT_WORK_USER> U_LABORANT_WORK_USER { get; set; }
        public DbSet<U_ALL_BARCODE_SCAN> U_ALL_BARCODE_SCAN { get; set; }
        public DbSet<U_ALL_BARCODE_SCAN_USER> U_ALL_BARCODE_SCAN_USER { get; set; }
        public DbSet<OPERATOR_USER> OPERATOR_USER { get; set; }
        public DbSet<WORKSTATION_USER> WORKSTATION_USER { get; set; }
        public DbSet<RTF_RESULT> RTF_RESULT { get; set; }
        public DbSet<U_SDG_ATTACHMENT> U_SDG_ATTACHMENT { get; set; }
        public DbSet<U_SDG_ATTACHMENT_USER> U_SDG_ATTACHMENT_USER { get; set; }
        public DbSet<U_NLIST_USER> U_NLIST_USER { get; set; }
        public DbSet<U_EXTRA_REQUEST> U_EXTRA_REQUEST { get; set; }
        public DbSet<U_EXTRA_REQUEST_DATA> U_EXTRA_REQUEST_DATA { get; set; }
        public DbSet<U_EXTRA_REQUEST_DATA_USER> U_EXTRA_REQUEST_DATA_USER { get; set; }
        public DbSet<U_EXTRA_REQUEST_USER> U_EXTRA_REQUEST_USER { get; set; }
        public DbSet<U_MORE_ACTION_USER> U_MORE_ACTION_USER { get; set; }
        public DbSet<U_MORE_ACTION> U_MORE_ACTION { get; set; }
        public DbSet<PAYMENT> PAYMENTs { get; set; }
        public DbSet<U_CONTAINER_MSG> U_CONTAINER_MSG { get; set; }
        public DbSet<U_CONTAINER_MSG_ROW> U_CONTAINER_MSG_ROW { get; set; }
        public DbSet<U_CONTAINER_MSG_ROW_USER> U_CONTAINER_MSG_ROW_USER { get; set; }
        public DbSet<U_SAMPLE_MSG> U_SAMPLE_MSG { get; set; }
        public DbSet<U_SAMPLE_MSG_USER> U_SAMPLE_MSG_USER { get; set; }
        public DbSet<U_SAMPLE_MSG_ROW_USER> U_SAMPLE_MSG_ROW_USER { get; set; }
        public DbSet<U_SAMPLE_MSG_ROW> U_SAMPLE_MSG_ROW { get; set; }
        public DbSet<U_CONTAINER_MSG_USER> U_CONTAINER_MSG_USER { get; set; }
        public DbSet<U_ASSUTA_CUSTOMER> U_ASSUTA_CUSTOMER { get; set; }
        public DbSet<U_ASSUTA_CUSTOMER_USER> U_ASSUTA_CUSTOMER_USER { get; set; }
        public DbSet<U_REQUEST_REMARK> U_REQUEST_REMARK { get; set; }
        public DbSet<U_NEW_RE_DESC> U_NEW_RE_DESC { get; set; }
        public DbSet<U_NEW_RE_DESC_USER> U_NEW_RE_DESC_USER { get; set; }
        public DbSet<RESULT_TEMPLATE> RESULT_TEMPLATE { get; set; }
        public DbSet<PATHOLOG_WORKLIST> PATHOLOG_WORKLIST { get; set; }
        public DbSet<SDG_DETAILS> SDG_DETAILS { get; set; }
        public DbSet<EXTRA_MATERIAL> EXTRA_MATERIAL { get; set; }
        public DbSet<EXTRA_SLIDES> EXTRA_SLIDES { get; set; }
        public DbSet<SDG_RESULTS> SDG_RESULTS { get; set; }
        public DbSet<U_CYTO_PRINT_CONTROL> U_CYTO_PRINT_CONTROL { get; set; }
        public DbSet<U_CYTO_PRINT_CONTROL_USER> U_CYTO_PRINT_CONTROL_USER { get; set; }
        public DbSet<EXTRA_CELL_BLOCK> EXTRA_CELL_BLOCK { get; set; }
        public DbSet<EXTRA_PAP_DILUTION> EXTRA_PAP_DILUTION { get; set; }
        public DbSet<SDG_LOG_CYTOLOGY> SDG_LOG_CYTOLOGY { get; set; }
        public DbSet<HISTOLOGY_BLOCK_LIST> HISTOLOGY_BLOCK_LIST { get; set; }
    }
}
