//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAUTILUS_DAINAMIC
    {
        public Nullable<decimal> CNTR { get; set; }
        public Nullable<System.DateTime> NOW_DATE { get; set; }
        public long D_ID { get; set; }
        public string D_NAME { get; set; }
        public string PATHO_NAME { get; set; }
        public Nullable<long> ASS_TO_PATHOLOD_ID { get; set; }
        public string ASS_TO_NAME { get; set; }
        public string SIGNBY_NAME { get; set; }
        public Nullable<decimal> SIGNBY_ID { get; set; }
        public Nullable<System.DateTime> D_CREAT_ON { get; set; }
        public Nullable<System.DateTime> D_AUTHO_ON { get; set; }
        public string TEST_CODE { get; set; }
        public string TEST_DESCRI { get; set; }
        public long S_ID { get; set; }
        public string S_NAME { get; set; }
        public string ORGAN { get; set; }
        public string SIDE { get; set; }
        public string S_PATHO_NAME { get; set; }
        public long A_ID { get; set; }
        public string A_NAME { get; set; }
        public Nullable<System.DateTime> SLIDE_CREATED { get; set; }
        public string A_TYPE { get; set; }
        public string STATION { get; set; }
        public string AAC { get; set; }
        public string COLOR { get; set; }
        public Nullable<System.DateTime> SEND_TO_PATHOLOG { get; set; }
        public string T_NAME { get; set; }
        public Nullable<System.DateTime> T_COMPLT { get; set; }
        public long R_ID { get; set; }
        public string R_NAME { get; set; }
        public string STATUS { get; set; }
        public string FORMATTED_RESULT { get; set; }
    }
}
