//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATOR_GROUP
    {
        public long GROUP_ID { get; set; }
        public long OPERATOR_ID { get; set; }
        public string ACCESS_LEVEL { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
    }
}
