//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATOR_USER
    {
        public long OPERATOR_ID { get; set; }
        public string U_DEGREE { get; set; }
        public string U_HEBREW_NAME { get; set; }
        public string U_LICENSE_NBR { get; set; }
        public Nullable<decimal> U_MANAGER_ORDER { get; set; }
        public Nullable<decimal> U_MATERIAL_RECEIVER { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
        public string U_PROFICIENCY { get; set; }
        public string U_PATHOLOG_MACRO { get; set; }
        public string U_SKIP_INSPECTION_PLAN { get; set; }
        public string U_PATHOLAB_WORKER_NBR { get; set; }
        public string U_DEPARTMENT { get; set; }
        public string U_PRINTER { get; set; }
        public string U_IS_ACTIVE { get; set; }
        public string U_IS_DIGITAL_PATHOLOG { get; set; }
    
        public virtual OPERATOR OPERATOR { get; set; }
    }
}
