//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORA_VW_ASPNET_PROFILES
    {
        public System.Guid USERID { get; set; }
        public System.DateTime LASTUPDATEDDATE { get; set; }
        public Nullable<decimal> DATASIZE { get; set; }
    }
}
