//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORA_VW_ASPNET_SESSIONS
    {
        public string SESSIONID { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime EXPIRES { get; set; }
        public System.DateTime LOCKDATE { get; set; }
        public System.DateTime LOCKDATELOCAL { get; set; }
        public decimal LOCKCOOKIE { get; set; }
        public decimal TIMEOUT { get; set; }
        public decimal LOCKED { get; set; }
        public Nullable<decimal> DATASIZE { get; set; }
        public decimal FLAGS { get; set; }
    }
}
