//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT_PAYMENT
    {
        public Nullable<decimal> U_ROW_NUM { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public long U_PAT_PAYMENT_ID { get; set; }
        public long U_SDG_ID { get; set; }
        public string U_INVC_NBR { get; set; }
        public string U_INVC_DATE { get; set; }
        public string U_MONTH { get; set; }
        public string U_YEAR_MONTH { get; set; }
        public string U_CLIENT_ID { get; set; }
        public string U_LAST_NAME { get; set; }
        public string U_FIRST_NAME { get; set; }
        public string U_COMMITMENT { get; set; }
        public string U_DATE_TAKEN { get; set; }
        public string U_LEUMIT_PART_NAME { get; set; }
        public string U_QNTY { get; set; }
        public string U_PRICE_INC_VAT { get; set; }
        public string U_AMOUNT_INC_VAT { get; set; }
        public string U_AMOUNT_NO_VAT { get; set; }
        public string U_PATHOLAB_NBR { get; set; }
        public string U_DEBIT_STATUS { get; set; }
        public string U_PRICE_NO_VAT { get; set; }
        public string U_PART_TEST { get; set; }
        public string U_SPECIAL_STAIN { get; set; }
        public string U_SDG_NAME { get; set; }
        public string U_CLALIT_CODE { get; set; }
        public string U_CLALIT_DESCR { get; set; }
        public string U_PART_CODE { get; set; }
        public string U_PART_GRP_NAME { get; set; }
        public string U_MEUHEDET_CODE { get; set; }
        public string U_PART_TYPE { get; set; }
        public string U_TYPE_LETTER { get; set; }
        public string U_ORDER_PART { get; set; }
        public Nullable<decimal> U_PRIORITY { get; set; }
        public string U_SDG_CREATED_ON { get; set; }
        public Nullable<decimal> U_NBR_OF_BLOCKS { get; set; }
        public Nullable<long> U_CUSTOMER_CODE { get; set; }
        public string U_CUSTOMER_NAME { get; set; }
        public string U_CLINIC_CODE { get; set; }
        public string U_DISTRICT { get; set; }
        public string U_CUSTOMER_GROUP { get; set; }
        public string U_ASCII_TYPE { get; set; }
        public string U_GROUP_NAME { get; set; }
        public string U_PHYSICIAN { get; set; }
        public string U_PHYSICIAN_LICENSE { get; set; }
    }
}
