//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public Nullable<decimal> ROW_NUM { get; set; }
        public long PAYMENT_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public long SDG_ID { get; set; }
        public string INVC_NBR { get; set; }
        public string INVC_DATE { get; set; }
        public string EVENT_DATE { get; set; }
        public string MONTH { get; set; }
        public string YEAR_MONTH { get; set; }
        public string CLIENT_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRAT_NAME { get; set; }
        public string IS_PASSPORT { get; set; }
        public string COMMITMENT { get; set; }
        public string DATE_TAKEN { get; set; }
        public string LEUMIT_PART_NAME { get; set; }
        public string QNTY { get; set; }
        public string PRICE_INC_VAT { get; set; }
        public string AMOUNT_INC_VAT { get; set; }
        public string AMOUNT_NO_VAT { get; set; }
        public string NBR { get; set; }
        public string DEBIT_STATUS { get; set; }
        public string PRICE_NO_VAT { get; set; }
        public string PART_TEST { get; set; }
        public string SPECIAL_STAIN { get; set; }
        public string SDG_NAME { get; set; }
        public string CLALIT_CODE { get; set; }
        public string CLALIT_DESCR { get; set; }
        public string PART_CODE { get; set; }
        public string PART_GRP_NAME { get; set; }
        public string MEUHEDET_CODE { get; set; }
        public string PART_TYPE { get; set; }
        public string TYPE_LETTER { get; set; }
        public string ORDER_PART { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string SDG_CREATED_ON { get; set; }
        public Nullable<decimal> NBR_OF_BLOCKS { get; set; }
        public Nullable<long> CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CLINIC_CODE { get; set; }
        public string DISTRICT { get; set; }
        public string CUSTOMER_GROUP { get; set; }
        public string ASCII_TYPE { get; set; }
        public string GROUP_NAME { get; set; }
        public string PHYSICIAN { get; set; }
        public string PHYSICIAN_LICENSE { get; set; }
        public string TZ_PASS { get; set; }
    }
}
