//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHRASE_ENTRY
    {
        public long PHRASE_ID { get; set; }
        public string PHRASE_NAME { get; set; }
        public string PHRASE_DESCRIPTION { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public string PHRASE_INFO { get; set; }
    
        public virtual PHRASE_HEADER PHRASE_HEADER { get; set; }
    }
}
