//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE_USER
    {
        public long SAMPLE_ID { get; set; }
        public string U_ASSISTANT_MACRO { get; set; }
        public Nullable<decimal> U_BIOPSY_NUMBER { get; set; }
        public Nullable<System.DateTime> U_DATE_ARRIVAL { get; set; }
        public string U_DECAL { get; set; }
        public string U_LIQUID_TYPE { get; set; }
        public string U_MARK { get; set; }
        public string U_MARK_AS { get; set; }
        public string U_MATERIAL { get; set; }
        public string U_MICRO_HEADER { get; set; }
        public string U_ORGAN { get; set; }
        public string U_ORGAN_CODE { get; set; }
        public Nullable<decimal> U_ORGAN_ID { get; set; }
        public string U_ORGAN_SIDE { get; set; }
        public string U_ORGAN_TOPOGRAPHY { get; set; }
        public string U_OVERNIGHT { get; set; }
        public string U_PATHOLOG_MACRO { get; set; }
        public string U_SAMPLE_CODE { get; set; }
        public string U_SAMPLE_FIX { get; set; }
        public string U_SAMPLE_TYPE { get; set; }
        public Nullable<decimal> U_VOLUME { get; set; }
        public string U_PROCEDURE_CODE { get; set; }
        public Nullable<long> U_PROCEDURE_ID { get; set; }
        public string U_ORGAN_REMARK { get; set; }
        public string U_TOPOGRAPHY { get; set; }
        public string U_TOPOGRAPHY_CODE { get; set; }
        public string U_ARCHIVE { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
        public string U_HISTOLOGY_SIZE { get; set; }
        public string U_TEST_CODE { get; set; }
        public string U_CYTOLOGY_NEXT_STEP { get; set; }
        public string U_CYTOLOGY_SLIDE_TYPE { get; set; }
        public string U_COLOR { get; set; }
        public string U_PATHOLAB_SAMPLE_NAME { get; set; }
        public Nullable<decimal> U_TUMOR_SIZE { get; set; }
        public string U_ASSUTA_NUMBER { get; set; }
        public string U_MACROPERSAMPLE { get; set; }
        public string U_MACRO_PER_SAMPLE { get; set; }
        public string U_MACRO { get; set; }
        public Nullable<System.DateTime> U_FORMALIN_ENTRY_DATE { get; set; }
    
        public virtual SAMPLE SAMPLE { get; set; }
    }
}
