//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMPLE
    {
        public SAMPLE()
        {
            this.ALIQUOTs = new HashSet<ALIQUOT>();
            this.SAMPLE1 = new HashSet<SAMPLE>();
        }
    
        public long SAMPLE_ID { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string ARCHIVED_CHILD_COMPLETE { get; set; }
        public Nullable<long> LOCATION_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> SDG_ID { get; set; }
        public Nullable<long> PREVIOUS_SAMPLE { get; set; }
        public Nullable<long> OPERATOR_ID { get; set; }
        public Nullable<long> CLIENT_ID { get; set; }
        public Nullable<System.DateTime> SAMPLED_ON { get; set; }
        public Nullable<long> SAMPLED_BY { get; set; }
        public Nullable<System.DateTime> DATE_RESULTS_REQUIRED { get; set; }
        public string EXTERNAL_REFERENCE { get; set; }
        public string CONCLUSION { get; set; }
        public Nullable<System.DateTime> EXPECTED_ON { get; set; }
        public string SAMPLE_TYPE { get; set; }
        public Nullable<long> INSPECTION_PLAN_ID { get; set; }
        public Nullable<long> SAMPLE_TEMPLATE_ID { get; set; }
        public Nullable<long> WORKFLOW_NODE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> COMPLETED_ON { get; set; }
        public Nullable<System.DateTime> AUTHORISED_ON { get; set; }
        public string EVENTS { get; set; }
        public string BLIND_SAMPLE { get; set; }
        public string NEEDS_REVIEW { get; set; }
        public Nullable<long> RECEIVED_BY { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string REPORTED { get; set; }
        public string HAS_NOTES { get; set; }
        public string HAS_AUDITS { get; set; }
        public Nullable<long> STUDY_ID { get; set; }
        public Nullable<long> COFA_TEMPLATE_ID { get; set; }
        public Nullable<long> REVIEW_TEMPLATE_ID { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<long> COMPLETED_BY { get; set; }
        public Nullable<long> AUTHORISED_BY { get; set; }
    
        public virtual ICollection<ALIQUOT> ALIQUOTs { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual INSPECTION_PLAN INSPECTION_PLAN { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual OPERATOR OPERATOR1 { get; set; }
        public virtual OPERATOR OPERATOR2 { get; set; }
        public virtual OPERATOR OPERATOR3 { get; set; }
        public virtual OPERATOR OPERATOR4 { get; set; }
        public virtual OPERATOR OPERATOR5 { get; set; }
        public virtual ICollection<SAMPLE> SAMPLE1 { get; set; }
        public virtual SAMPLE SAMPLE2 { get; set; }
        public virtual SDG SDG { get; set; }
        public virtual SAMPLE_USER SAMPLE_USER { get; set; }
        public virtual WORKFLOW_NODE WORKFLOW_NODE { get; set; }
    }
}
