//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEMA_TABLE
    {
        public SCHEMA_TABLE()
        {
            this.U_REPORT_PARAMS_USER = new HashSet<U_REPORT_PARAMS_USER>();
            this.SCHEMA_TABLE1 = new HashSet<SCHEMA_TABLE>();
            this.SCHEMA_TABLE11 = new HashSet<SCHEMA_TABLE>();
        }
    
        public long SCHEMA_TABLE_ID { get; set; }
        public Nullable<long> SCHEMA_ARCHIVED_SET_ID { get; set; }
        public string NAME { get; set; }
        public string DATABASE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string USER_DEFINED { get; set; }
        public string NEEDS_ARCHIVING { get; set; }
        public string ARCHIVED { get; set; }
        public string ARCHIVING_OBJECT { get; set; }
        public Nullable<long> EXTRA_TABLE_ID { get; set; }
        public Nullable<long> ACTIVE_TABLE_ID { get; set; }
        public string EXPORTABLE { get; set; }
    
        public virtual ICollection<U_REPORT_PARAMS_USER> U_REPORT_PARAMS_USER { get; set; }
        public virtual ICollection<SCHEMA_TABLE> SCHEMA_TABLE1 { get; set; }
        public virtual SCHEMA_TABLE SCHEMA_TABLE2 { get; set; }
        public virtual ICollection<SCHEMA_TABLE> SCHEMA_TABLE11 { get; set; }
        public virtual SCHEMA_TABLE SCHEMA_TABLE3 { get; set; }
    }
}
