//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG
    {
        public SDG()
        {
            this.SAMPLEs = new HashSet<SAMPLE>();
            this.U_SPECIAL_INSPECTION_USER = new HashSet<U_SPECIAL_INSPECTION_USER>();
            this.U_SDG_ATTACHMENT_USER = new HashSet<U_SDG_ATTACHMENT_USER>();
            this.U_EXTRA_REQUEST_USER = new HashSet<U_EXTRA_REQUEST_USER>();
            this.U_MORE_ACTION_USER = new HashSet<U_MORE_ACTION_USER>();
        }
    
        public long SDG_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string ARCHIVED_CHILD_COMPLETE { get; set; }
        public Nullable<long> SDG_TEMPLATE_ID { get; set; }
        public Nullable<long> WORKFLOW_NODE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string OLD_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> COMPLETED_ON { get; set; }
        public Nullable<System.DateTime> AUTHORISED_ON { get; set; }
        public string EVENTS { get; set; }
        public string NEEDS_REVIEW { get; set; }
        public Nullable<long> INSPECTION_PLAN_ID { get; set; }
        public Nullable<long> RECEIVED_BY { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string REPORTED { get; set; }
        public string HAS_NOTES { get; set; }
        public string CONCLUSION { get; set; }
        public string HAS_AUDITS { get; set; }
        public string EXTERNAL_REFERENCE { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<long> COMPLETED_BY { get; set; }
        public Nullable<long> AUTHORISED_BY { get; set; }
    
        public virtual INSPECTION_PLAN INSPECTION_PLAN { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual OPERATOR OPERATOR1 { get; set; }
        public virtual OPERATOR OPERATOR2 { get; set; }
        public virtual OPERATOR OPERATOR3 { get; set; }
        public virtual ICollection<SAMPLE> SAMPLEs { get; set; }
        public virtual ICollection<U_SPECIAL_INSPECTION_USER> U_SPECIAL_INSPECTION_USER { get; set; }
        public virtual SDG_USER SDG_USER { get; set; }
        public virtual WORKFLOW_NODE WORKFLOW_NODE { get; set; }
        public virtual ICollection<U_SDG_ATTACHMENT_USER> U_SDG_ATTACHMENT_USER { get; set; }
        public virtual ICollection<U_EXTRA_REQUEST_USER> U_EXTRA_REQUEST_USER { get; set; }
        public virtual ICollection<U_MORE_ACTION_USER> U_MORE_ACTION_USER { get; set; }
    }
}
