//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG_LOG
    {
        public long SDG_ID { get; set; }
        public System.DateTime TIME { get; set; }
        public string APPLICATION_CODE { get; set; }
        public Nullable<long> SESSION_ID { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
