//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG_SAMPLE_ANALYSIS
    {
        public long SDG_ID { get; set; }
        public string DIAGNOSIS { get; set; }
        public string ORGANS { get; set; }
        public Nullable<decimal> NUM_OF_BLOCKS { get; set; }
        public Nullable<decimal> NUM_OF_COLORS { get; set; }
        public string HAS_SLIDES_SCANNED { get; set; }
    }
}
