//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG_LOG_CYTOLOGY
    {
        public long SDG_ID { get; set; }
        public string NAME { get; set; }
        public string U_PATHOLAB_NUMBER { get; set; }
        public string LAST_APPLICATION_CODE { get; set; }
        public string PATHOLOG_NAME { get; set; }
        public string INFO { get; set; }
        public Nullable<System.DateTime> RECEIVED_ON { get; set; }
        public string ENTITY { get; set; }
        public string PRIORITY { get; set; }
        public string PART { get; set; }
    }
}
