//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG_COUNT
    {
        public Nullable<decimal> ROW_NUM { get; set; }
        public long SDG_ID { get; set; }
        public string MONTH_YEAR { get; set; }
        public string YEAR_MONTH { get; set; }
        public string CLIENT_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRAT_NAME { get; set; }
        public string PATHOLAB_NBR { get; set; }
        public string SDG_NAME { get; set; }
        public string ORDER_PART { get; set; }
        public Nullable<System.DateTime> SDG_CREATED_ON { get; set; }
        public Nullable<decimal> NBR_OF_BLOCKS { get; set; }
        public Nullable<decimal> CNT_BLOCK { get; set; }
        public Nullable<decimal> CNT_SLIDE { get; set; }
        public Nullable<long> CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CLINIC_CODE { get; set; }
        public string DISTRICT { get; set; }
        public string CUSTOMER_GROUP { get; set; }
        public string GROUP_NAME { get; set; }
        public string PHYSICIAN { get; set; }
        public string PHYSICIAN_LICENSE { get; set; }
        public string RECEIVED_BY_NAME { get; set; }
        public string LABORANT_NAME { get; set; }
        public string SECRITERY_NAME { get; set; }
        public string SIGN_BY_1 { get; set; }
        public string SIGN_BY_2 { get; set; }
        public string SIGN_BY_3 { get; set; }
        public string RESULT_POS { get; set; }
    }
}
