//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDG_DETAILS
    {
        public long SDG_ID { get; set; }
        public string SDG_NAME { get; set; }
        public string STATUS { get; set; }
        public string PATHOLAB_NUMBER { get; set; }
        public string U_PDF_PATH { get; set; }
        public string U_ATFILENM { get; set; }
        public string U_TUMOR_SIZE { get; set; }
        public string U_IS_QC { get; set; }
        public Nullable<decimal> U_WEEK_NBR { get; set; }
        public Nullable<long> U_PATHOLOG { get; set; }
        public string CONTAINER_NAME { get; set; }
        public Nullable<System.DateTime> CONTAINER_RECEIVE { get; set; }
        public string CLINIC_NAME { get; set; }
        public string PARTS_NAME { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string IMPLEMENTING_CLINIC { get; set; }
        public string IMPLEMENTING_CLINIC_CODE { get; set; }
        public string ANOTHER_INSURER { get; set; }
        public string ACCORD_NUMBER { get; set; }
        public Nullable<decimal> HOSPITAL_NUMBER { get; set; }
        public string PRIORITY { get; set; }
        public string IMPLEMENTING_PHYSICIAN_LICENSE { get; set; }
        public string IMPLEMENTING_PHYSICIAN_PHONE { get; set; }
        public string IMPLEMENTING_PHYSICIAN_DEGREE { get; set; }
        public string IMPLEMENTING_PHYSICIAN_FNAME { get; set; }
        public string IMPLEMENTING_PHYSICIAN_LNAME { get; set; }
        public string IMPLEMENTING_PHYSICIAN_FULL_NAME { get; set; }
        public string REFERRING_PHYSICIAN_LICENSE { get; set; }
        public string REFERRING_PHYSICIAN_PHONE { get; set; }
        public string REFERRING_PHYSICIAN_DEGREE { get; set; }
        public string REFERRING_PHYSICIAN_FNAME { get; set; }
        public string REFERRING_PHYSICIAN_LNAME { get; set; }
        public string REFERRING_PHYSICIAN_FULL_NAME { get; set; }
        public string U_PATHOLOG_MACRO { get; set; }
        public string REFERRAL_CLINIC_NAME { get; set; }
        public string REFERRAL_CLINIC_CODE { get; set; }
        public string CLIENT_PASSPORT { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_LNAME { get; set; }
        public string CLIENT_PREV_LNAME { get; set; }
        public string CLIENT_FNAME { get; set; }
        public string CLIENT_PHONE { get; set; }
        public string CLIENT_GENDER { get; set; }
        public Nullable<System.DateTime> CLIENT_BDAY { get; set; }
        public string REMARK_DESCRIPTION { get; set; }
        public string REMARK_STATUS { get; set; }
        public string TYPED_BY { get; set; }
        public string INTENDED_PATHOLOG { get; set; }
        public Nullable<System.DateTime> DATE_HAFNAYA { get; set; }
        public Nullable<System.DateTime> DATE_AGAA { get; set; }
        public Nullable<System.DateTime> DATE_KABALA { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETED { get; set; }
        public Nullable<System.DateTime> DATE_AUTHORISED { get; set; }
        public Nullable<decimal> EXTRAREQ_COUNT { get; set; }
        public Nullable<decimal> SDGATTACH_COUNT { get; set; }
        public string u_isConsult { get; set; }
    }
}
