//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_USER
    {
        public long SUPPLIER_ID { get; set; }
        public string U_DEGREE { get; set; }
        public string U_FIRST_NAME { get; set; }
        public string U_LAST_NAME { get; set; }
        public string U_ID_NBR { get; set; }
        public string U_LICENSE_NBR { get; set; }
        public string U_PROFICENCY { get; set; }
        public string U_EMAIL_ADDRESS { get; set; }
        public string U_SEND_CODED_LETTER { get; set; }
        public string U_PHONE_NBR { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
