//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public SUPPLIER()
        {
            this.ALIQUOTs = new HashSet<ALIQUOT>();
            this.SDG_USER = new HashSet<SDG_USER>();
            this.SDG_USER1 = new HashSet<SDG_USER>();
            this.SUPPLIER1 = new HashSet<SUPPLIER>();
            this.U_SAMPLE_MSG_USER = new HashSet<U_SAMPLE_MSG_USER>();
            this.U_SAMPLE_MSG_USER1 = new HashSet<U_SAMPLE_MSG_USER>();
        }
    
        public long SUPPLIER_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
        public string SUPPLIER_TYPE { get; set; }
        public string SUPPLIER_CODE { get; set; }
    
        public virtual ICollection<ALIQUOT> ALIQUOTs { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER1 { get; set; }
        public virtual ICollection<SUPPLIER> SUPPLIER1 { get; set; }
        public virtual SUPPLIER SUPPLIER2 { get; set; }
        public virtual SUPPLIER_USER SUPPLIER_USER { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_USER> U_SAMPLE_MSG_USER { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_USER> U_SAMPLE_MSG_USER1 { get; set; }
    }
}
