//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_ALL_BARCODE_SCAN_USER
    {
        public long U_ALL_BARCODE_SCAN_ID { get; set; }
        public string U_LABORANT_POSITION { get; set; }
        public Nullable<long> U_LABORANT { get; set; }
        public string U_PRINTER { get; set; }
        public Nullable<long> U_ALIQUOT_NAME { get; set; }
        public Nullable<System.DateTime> U_CREATED_ON { get; set; }
        public Nullable<decimal> U_NUMBER_OF_SLIDES { get; set; }
        public string U_STATUS { get; set; }
        public string U_ENTITY_NAME { get; set; }
    
        public virtual ALIQUOT ALIQUOT { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual U_ALL_BARCODE_SCAN U_ALL_BARCODE_SCAN { get; set; }
    }
}
