//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_ASSUTA_CUSTOMER_USER
    {
        public long U_ASSUTA_CUSTOMER_ID { get; set; }
        public string U_ASSUTA_CUSTOMER_NAME { get; set; }
        public string U_ASSUTA_CLINIC_CODE { get; set; }
        public Nullable<long> U_PATHOLAB_CUSTOMER_CODE { get; set; }
        public Nullable<long> U_PATHOLAB_SECOND_CUSTOMER { get; set; }
        public Nullable<decimal> U_PRIORITY { get; set; }
        public Nullable<long> U_ASSUTA_CLINIC { get; set; }
    
        public virtual U_ASSUTA_CUSTOMER U_ASSUTA_CUSTOMER { get; set; }
        public virtual U_CLINIC U_CLINIC { get; set; }
        public virtual U_CUSTOMER U_CUSTOMER { get; set; }
        public virtual U_CUSTOMER U_CUSTOMER1 { get; set; }
    }
}
