//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CLINIC
    {
        public U_CLINIC()
        {
            this.SDG_USER = new HashSet<SDG_USER>();
            this.SDG_USER1 = new HashSet<SDG_USER>();
            this.SDG_USER2 = new HashSet<SDG_USER>();
            this.U_CLINIC1 = new HashSet<U_CLINIC>();
            this.U_CONTAINER_USER = new HashSet<U_CONTAINER_USER>();
            this.U_START_SCREEN_USER = new HashSet<U_START_SCREEN_USER>();
            this.U_SAMPLE_MSG_USER = new HashSet<U_SAMPLE_MSG_USER>();
            this.U_CONTAINER_MSG_USER = new HashSet<U_CONTAINER_MSG_USER>();
            this.U_ASSUTA_CUSTOMER_USER = new HashSet<U_ASSUTA_CUSTOMER_USER>();
        }
    
        public long U_CLINIC_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER1 { get; set; }
        public virtual ICollection<SDG_USER> SDG_USER2 { get; set; }
        public virtual ICollection<U_CLINIC> U_CLINIC1 { get; set; }
        public virtual U_CLINIC U_CLINIC2 { get; set; }
        public virtual ICollection<U_CONTAINER_USER> U_CONTAINER_USER { get; set; }
        public virtual ICollection<U_START_SCREEN_USER> U_START_SCREEN_USER { get; set; }
        public virtual U_CLINIC_USER U_CLINIC_USER { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_USER> U_SAMPLE_MSG_USER { get; set; }
        public virtual ICollection<U_CONTAINER_MSG_USER> U_CONTAINER_MSG_USER { get; set; }
        public virtual ICollection<U_ASSUTA_CUSTOMER_USER> U_ASSUTA_CUSTOMER_USER { get; set; }
    }
}
