//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CLINIC_USER
    {
        public long U_CLINIC_ID { get; set; }
        public string U_DISTRICT { get; set; }
        public string U_FAX_NBR { get; set; }
        public string U_CLINIC_NAME { get; set; }
        public string U_EX_NUMBER { get; set; }
        public string U_GRP_CODE { get; set; }
        public string U_GRP_NAME { get; set; }
        public string U_CUSTOMER_CODE { get; set; }
        public Nullable<long> U_CUSTOMER_ID { get; set; }
        public string U_CLINIC_CODE { get; set; }
        public string U_EMAIL_ADDRESS { get; set; }
        public string U_SENDER { get; set; }
        public string U_PRIVATE_LIBRARY { get; set; }
        public string U_ASSUTA_CLINIC_CODE { get; set; }
        public string U_ASSUTA_DIVISION_CODE { get; set; }
        public string U_SEND_CODED_LETTER { get; set; }
    
        public virtual U_CLINIC U_CLINIC { get; set; }
        public virtual U_CUSTOMER U_CUSTOMER { get; set; }
    }
}
