//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CONTAINER_MSG_ROW_USER
    {
        public long U_CONTAINER_MSG_ROW_ID { get; set; }
        public string U_REQUEST { get; set; }
        public Nullable<long> U_MSG_ID { get; set; }
        public Nullable<System.DateTime> U_PACKED_ON { get; set; }
    
        public virtual U_CONTAINER_MSG U_CONTAINER_MSG { get; set; }
        public virtual U_CONTAINER_MSG_ROW U_CONTAINER_MSG_ROW { get; set; }
    }
}
