//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CRYSTAL_REPORT_USER
    {
        public long U_CRYSTAL_REPORT_ID { get; set; }
        public string U_HEBREW_NAME { get; set; }
        public string U_LIST { get; set; }
        public string U_BOLD { get; set; }
        public string U_UNDERLINE { get; set; }
        public string U_ROLE_ALLOWED { get; set; }
        public string U_PATH { get; set; }
        public string U_COLUMN { get; set; }
        public string U_LABEL { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
    
        public virtual U_CRYSTAL_REPORT U_CRYSTAL_REPORT { get; set; }
    }
}
