//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CUSTOMER_USER
    {
        public long U_CUSTOMER_ID { get; set; }
        public string U_CUSTOMER_CODE { get; set; }
        public string U_CUSTOMER_NAME { get; set; }
        public string U_CUSTOMER_LTN_NAME { get; set; }
        public string U_CUSTOMER_TYPE { get; set; }
        public string U_CUSTOMER_GROUP { get; set; }
        public string U_LETTER_B { get; set; }
        public string U_LETTER_C { get; set; }
        public string U_LETTER_P { get; set; }
        public string U_INC_VAT { get; set; }
        public string U_PAY_TRANSPORT { get; set; }
        public Nullable<decimal> U_SMALL_UP_TO { get; set; }
        public Nullable<decimal> U_MEDIUM_UP_TO { get; set; }
        public Nullable<decimal> U_LARGE_UP_TO { get; set; }
        public string U_PRIVATE_LIBRARY { get; set; }
        public Nullable<long> U_PRICE_LIST_ID { get; set; }
        public string U_PRICE_LIST_NAME { get; set; }
        public string U_DISTRICT { get; set; }
        public string U_GRP_CLINIC_CODE { get; set; }
        public string U_FAX_NBR { get; set; }
        public string U_EMAIL_ADDRESS { get; set; }
        public string U_CLALIT { get; set; }
        public string U_ASCII_TYPE { get; set; }
        public string U_PRICE_LEVEL { get; set; }
        public string U_SEND_CODED_LETTER { get; set; }
        public Nullable<decimal> U_XL_UP_TO { get; set; }
        public Nullable<decimal> U_INITIAL_NBR_B { get; set; }
        public Nullable<decimal> U_INITIAL_NBR_P { get; set; }
        public Nullable<decimal> U_INITIAL_NBR_C { get; set; }
    
        public virtual U_CUSTOMER U_CUSTOMER { get; set; }
        public virtual U_PRICE_LIST U_PRICE_LIST { get; set; }
    }
}
