//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_CYTO_PRINT_CONTROL_USER
    {
        public long U_CYTO_PRINT_CONTROL_ID { get; set; }
        public Nullable<System.DateTime> U_DATE_PRINT { get; set; }
    
        public virtual U_CYTO_PRINT_CONTROL U_CYTO_PRINT_CONTROL { get; set; }
    }
}
