//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_DEBIT
    {
        public U_DEBIT()
        {
            this.U_DEBIT1 = new HashSet<U_DEBIT>();
            this.ALIQUOT_USER = new HashSet<ALIQUOT_USER>();
        }
    
        public long U_DEBIT_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_DEBIT> U_DEBIT1 { get; set; }
        public virtual U_DEBIT U_DEBIT2 { get; set; }
        public virtual U_DEBIT_USER U_DEBIT_USER { get; set; }
        public virtual ICollection<ALIQUOT_USER> ALIQUOT_USER { get; set; }
    }
}
