//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_DEBIT_USER
    {
        public long U_DEBIT_ID { get; set; }
        public Nullable<long> U_ORDER_ID { get; set; }
        public string U_SDG_NAME { get; set; }
        public Nullable<System.DateTime> U_EVENT_DATE { get; set; }
        public Nullable<long> U_PARTS_ID { get; set; }
        public string U_PART_TEXT { get; set; }
        public Nullable<decimal> U_PART_PRICE { get; set; }
        public Nullable<decimal> U_PRICE_INC_VAT { get; set; }
        public Nullable<decimal> U_QUANTITY { get; set; }
        public Nullable<decimal> U_LINE_AMOUNT { get; set; }
        public string U_ENTITY_ID { get; set; }
        public string U_DEBIT_STATUS { get; set; }
        public string U_INVC_NBR { get; set; }
        public Nullable<System.DateTime> U_INVC_DATE { get; set; }
        public Nullable<System.DateTime> U_LAST_UPDATE { get; set; }
    
        public virtual U_DEBIT U_DEBIT { get; set; }
        public virtual U_ORDER U_ORDER { get; set; }
        public virtual U_PARTS U_PARTS { get; set; }
    }
}
