//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_DRIVER_USER
    {
        public long U_DRIVER_ID { get; set; }
        public string U_CODE { get; set; }
    
        public virtual U_DRIVER U_DRIVER { get; set; }
    }
}
