//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_DRIVER
    {
        public U_DRIVER()
        {
            this.U_DRIVER1 = new HashSet<U_DRIVER>();
            this.U_CONTAINER_MSG_USER = new HashSet<U_CONTAINER_MSG_USER>();
            this.U_CONTAINER_USER = new HashSet<U_CONTAINER_USER>();
        }
    
        public long U_DRIVER_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_DRIVER> U_DRIVER1 { get; set; }
        public virtual U_DRIVER U_DRIVER2 { get; set; }
        public virtual ICollection<U_CONTAINER_MSG_USER> U_CONTAINER_MSG_USER { get; set; }
        public virtual U_DRIVER_USER U_DRIVER_USER { get; set; }
        public virtual ICollection<U_CONTAINER_USER> U_CONTAINER_USER { get; set; }
    }
}
