//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_EXTRA_REQUEST_DATA_USER
    {
        public long U_EXTRA_REQUEST_DATA_ID { get; set; }
        public string U_DESC { get; set; }
        public string U_ENTITY_TYPE { get; set; }
        public Nullable<long> U_EXTRA_REQUEST_ID { get; set; }
        public Nullable<System.DateTime> U_LAB_ON { get; set; }
        public string U_REQUEST_DETAILS { get; set; }
        public string U_SLIDE_NAME { get; set; }
        public string U_STATUS { get; set; }
        public string U_REQ_TYPE { get; set; }
        public string U_REMARKS { get; set; }
    
        public virtual U_EXTRA_REQUEST U_EXTRA_REQUEST { get; set; }
        public virtual U_EXTRA_REQUEST_DATA U_EXTRA_REQUEST_DATA { get; set; }
    }
}
