//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_EXTRA_REQUEST_USER
    {
        public long U_EXTRA_REQUEST_ID { get; set; }
        public Nullable<long> U_CREATED_BY { get; set; }
        public Nullable<System.DateTime> U_CREATED_ON { get; set; }
        public Nullable<long> U_SDG_ID { get; set; }
        public string U_STATUS { get; set; }
    
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual SDG SDG { get; set; }
        public virtual U_EXTRA_REQUEST U_EXTRA_REQUEST { get; set; }
    }
}
