//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_EXTRA_REQUEST_DATA
    {
        public U_EXTRA_REQUEST_DATA()
        {
            this.U_EXTRA_REQUEST_DATA1 = new HashSet<U_EXTRA_REQUEST_DATA>();
        }
    
        public long U_EXTRA_REQUEST_DATA_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_EXTRA_REQUEST_DATA> U_EXTRA_REQUEST_DATA1 { get; set; }
        public virtual U_EXTRA_REQUEST_DATA U_EXTRA_REQUEST_DATA2 { get; set; }
        public virtual U_EXTRA_REQUEST_DATA_USER U_EXTRA_REQUEST_DATA_USER { get; set; }
    }
}
