//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_LABORANT_WORK_USER
    {
        public long U_LABORANT_WORK_ID { get; set; }
        public string U_LABORANT_POSITION { get; set; }
        public Nullable<long> U_LABORANT { get; set; }
        public string U_BARCODE_READER { get; set; }
        public Nullable<System.DateTime> U_STARTED_ON { get; set; }
        public Nullable<System.DateTime> U_STOPED_ON { get; set; }
        public string U_STATUS { get; set; }
        public Nullable<decimal> U_TOTAL_NUMBER_BARCODE { get; set; }
    
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual U_LABORANT_WORK U_LABORANT_WORK { get; set; }
    }
}
