//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_MORE_ACTION_USER
    {
        public long U_MORE_ACTION_ID { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        public string U_ACTION_TYPE { get; set; }
        public string U_HANDED_TO { get; set; }
        public Nullable<decimal> U_NUMBER_OF_SLIDE { get; set; }
        public string U_AGREE { get; set; }
        public string U_STATUS { get; set; }
        public Nullable<long> U_SDG_ID { get; set; }
    
        public virtual SDG SDG { get; set; }
        public virtual U_MORE_ACTION U_MORE_ACTION { get; set; }
    }
}
