//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_NEW_RE_DESC_USER
    {
        public long U_NEW_RE_DESC_ID { get; set; }
        public Nullable<long> U_RESULT_TEMPLATE_ID { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
        public string U_GROUP { get; set; }
    
        public virtual U_NEW_RE_DESC U_NEW_RE_DESC { get; set; }
        public virtual RESULT_TEMPLATE RESULT_TEMPLATE { get; set; }
    }
}
