//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_NLIST_USER
    {
        public long U_NLIST_ID { get; set; }
        public string U_SDG_TYPE { get; set; }
        public string U_TEXT { get; set; }
        public string U_ORGANS { get; set; }
        public string U_OPERATORS_ID { get; set; }
    }
}
