//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_NORGAN_USER
    {
        public long U_NORGAN_ID { get; set; }
        public string U_ORGAN_CODE { get; set; }
        public string U_ORGAN_HEBREW_NAME { get; set; }
        public string U_ORGAN_NAME { get; set; }
        public string U_ORGAN_TYPE { get; set; }
        public string U_IS_ACTIVE { get; set; }
    
        public virtual U_NORGAN U_NORGAN { get; set; }
    }
}
