//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_ORDER_USER
    {
        public long U_ORDER_ID { get; set; }
        public string U_STATUS { get; set; }
        public Nullable<System.DateTime> U_CREATED_ON { get; set; }
        public string U_INC_VAT { get; set; }
        public Nullable<decimal> U_TOTAL_DEBIT { get; set; }
        public string U_IN_ADVANCE { get; set; }
        public string U_SDG_NAME { get; set; }
        public Nullable<long> U_CUSTOMER { get; set; }
        public Nullable<long> U_SECOND_CUSTOMER { get; set; }
        public string U_URGENT { get; set; }
        public Nullable<long> U_PARTS_ID { get; set; }
        public string U_PAY_TYPE { get; set; }
        public Nullable<decimal> U_PAY_AMOUNT { get; set; }
    
        public virtual U_CUSTOMER U_CUSTOMER1 { get; set; }
        public virtual U_CUSTOMER U_CUSTOMER2 { get; set; }
        public virtual U_ORDER U_ORDER { get; set; }
        public virtual U_PARTS U_PARTS { get; set; }
    }
}
