//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_PARTS
    {
        public U_PARTS()
        {
            this.U_DEBIT_USER = new HashSet<U_DEBIT_USER>();
            this.U_ORDER_USER = new HashSet<U_ORDER_USER>();
            this.U_PARTS1 = new HashSet<U_PARTS>();
            this.U_PRICE_LIST_USER = new HashSet<U_PRICE_LIST_USER>();
            this.U_PARTS_USER1 = new HashSet<U_PARTS_USER>();
        }
    
        public long U_PARTS_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_DEBIT_USER> U_DEBIT_USER { get; set; }
        public virtual ICollection<U_ORDER_USER> U_ORDER_USER { get; set; }
        public virtual ICollection<U_PARTS> U_PARTS1 { get; set; }
        public virtual U_PARTS U_PARTS2 { get; set; }
        public virtual ICollection<U_PRICE_LIST_USER> U_PRICE_LIST_USER { get; set; }
        public virtual U_PARTS_USER U_PARTS_USER { get; set; }
        public virtual ICollection<U_PARTS_USER> U_PARTS_USER1 { get; set; }
    }
}
