//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_PARTS_USER
    {
        public long U_PARTS_ID { get; set; }
        public string U_PART_CODE { get; set; }
        public string U_LTN_NAME { get; set; }
        public string U_PART_CLALIT_CODE { get; set; }
        public string U_PART_CLALIT_DESCR { get; set; }
        public string U_PART_LEUMIT_CODE { get; set; }
        public string U_PART_MEUHEDET_CODE { get; set; }
        public string U_QUERY { get; set; }
        public string U_GRP_CODE { get; set; }
        public string U_GRP_NAME { get; set; }
        public string U_DISPLAY_ON_PRICE_LIST { get; set; }
        public string U_PART_TYPE { get; set; }
        public string U_STAIN { get; set; }
        public Nullable<long> U_SDG_WORKFLOW { get; set; }
        public Nullable<long> U_EXTRA_SAMPLE_WORKFLOW { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
        public Nullable<long> U_PART_DEFAULT_STAIN { get; set; }
        public string U_REPORT_TO_HEALTH_MINISTR { get; set; }
        public string U_ONLY_ON_MALIGNANCY { get; set; }
        public string U_ASSUTA_CODE { get; set; }
        public Nullable<long> U_FIRST_SAMPLE_WORKFLOW { get; set; }
        public string U_PROTOCOL_NAME { get; set; }
        public Nullable<decimal> U_PROTOCOL_NUMBER { get; set; }
        public string U_PART_MEUCHEDET_DESC { get; set; }
    
        public virtual U_PARTS U_PARTS { get; set; }
        public virtual WORKFLOW SAMPLE_WORKFLOW { get; set; }
        public virtual WORKFLOW SDG_WORKFLOW { get; set; }
        public virtual U_PARTS DEFAULT_STAIN { get; set; }
        public virtual WORKFLOW WORKFLOW1 { get; set; }
    }
}
