//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_REPORT_PARAMS_USER
    {
        public long U_REPORT_PARAMS_ID { get; set; }
        public Nullable<long> U_REPORT_ID { get; set; }
        public string U_PARAM_CODE { get; set; }
        public string U_FIELD_TYPE { get; set; }
        public string U_PARAM_HEBREW { get; set; }
        public string U_TABLE_NAME { get; set; }
        public string U_FIELD_NAME { get; set; }
        public string U_PARAM_ENTRY_TYPE { get; set; }
        public string U_PARAM_TYPE { get; set; }
        public string U_REPORT_NAME { get; set; }
        public Nullable<long> U_TABLE { get; set; }
        public Nullable<long> U_PHRASE_HEADER { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
    
        public virtual U_CRYSTAL_REPORT U_CRYSTAL_REPORT { get; set; }
        public virtual U_REPORT_PARAMS U_REPORT_PARAMS { get; set; }
        public virtual PHRASE_HEADER PHRASE_HEADER { get; set; }
        public virtual SCHEMA_TABLE SCHEMA_TABLE { get; set; }
    }
}
