//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SAMPLE_MSG_USER
    {
        public long U_SAMPLE_MSG_ID { get; set; }
        public string U_CASE_FILE { get; set; }
        public string U_REQUEST_NUM { get; set; }
        public string U_INSTNAME { get; set; }
        public Nullable<long> U_CLIENT_ID { get; set; }
        public Nullable<long> U_CLINIC_ID { get; set; }
        public Nullable<long> U_REFERRING_PHYSICIAN { get; set; }
        public Nullable<long> U_IMPLEMENTING_PHYSICIAN { get; set; }
        public string U_ERRORS { get; set; }
        public string U_PATH { get; set; }
        public string U_TEST_TYPE_CODE { get; set; }
        public string U_PDF { get; set; }
        public Nullable<System.DateTime> U_EXECUTE_TIME { get; set; }
        public Nullable<long> U_ORDER_ID { get; set; }
        public string U_STATUS { get; set; }
        public string U_UPDATE_NUMBER { get; set; }
        public string U_UPDATE_REASON { get; set; }
        public string U_PRIORITY { get; set; }
        public string U_PATIENT_NAME { get; set; }
        public string U_PATIENT_FIRST_NAME { get; set; }
        public string U_PATIENT_LAST_NAME { get; set; }
        public string U_PATIENT_GENDER { get; set; }
        public string U_PATIENT_ID_TYPE { get; set; }
        public string U_PATIENT_BD { get; set; }
        public string U_MESSAGE_TYPE { get; set; }
        public string U_REQ_NUM_LAB { get; set; }
        public string U_SUP_CODE { get; set; }
        public string U_REF_PHYSICIAN_NBR { get; set; }
        public string U_REF_PHYSICIAN_NAME { get; set; }
        public string U_IMP_PHYSICIAN_ID { get; set; }
        public string U_IMP_PHYSICIAN_NAME { get; set; }
        public string U_IMP_PHYSICIAN_NBR { get; set; }
        public Nullable<System.DateTime> U_CREATED_ON { get; set; }
        public string U_CLINIC_UNIT { get; set; }
        public string U_CLINIC_HOS { get; set; }
    
        public virtual U_SAMPLE_MSG U_SAMPLE_MSG { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual U_CLINIC U_CLINIC { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual SUPPLIER SUPPLIER1 { get; set; }
        public virtual U_ORDER U_ORDER { get; set; }
    }
}
