//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SAMPLE_MSG
    {
        public U_SAMPLE_MSG()
        {
            this.U_SAMPLE_MSG1 = new HashSet<U_SAMPLE_MSG>();
            this.U_SAMPLE_MSG_ROW_USER = new HashSet<U_SAMPLE_MSG_ROW_USER>();
        }
    
        public long U_SAMPLE_MSG_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_SAMPLE_MSG> U_SAMPLE_MSG1 { get; set; }
        public virtual U_SAMPLE_MSG U_SAMPLE_MSG2 { get; set; }
        public virtual U_SAMPLE_MSG_USER U_SAMPLE_MSG_USER { get; set; }
        public virtual ICollection<U_SAMPLE_MSG_ROW_USER> U_SAMPLE_MSG_ROW_USER { get; set; }
    }
}
