//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SAMPLE_MSG_ROW_USER
    {
        public long U_SAMPLE_MSG_ROW_ID { get; set; }
        public Nullable<long> U_SAMPLE_MSG_ID { get; set; }
        public string U_TEST_CODE { get; set; }
        public string U_SAMPLE_BARCODE { get; set; }
    
        public virtual U_SAMPLE_MSG U_SAMPLE_MSG { get; set; }
        public virtual U_SAMPLE_MSG_ROW U_SAMPLE_MSG_ROW { get; set; }
    }
}
