//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SDG_ATTACHMENT_USER
    {
        public long U_SDG_ATTACHMENT_ID { get; set; }
        public string U_TITLE { get; set; }
        public string U_PATH { get; set; }
        public Nullable<long> U_SDG_ID { get; set; }
    
        public virtual SDG SDG { get; set; }
        public virtual U_SDG_ATTACHMENT U_SDG_ATTACHMENT { get; set; }
    }
}
