//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SDG_ATTACHMENT
    {
        public U_SDG_ATTACHMENT()
        {
            this.U_SDG_ATTACHMENT1 = new HashSet<U_SDG_ATTACHMENT>();
        }
    
        public long U_SDG_ATTACHMENT_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_SDG_ATTACHMENT> U_SDG_ATTACHMENT1 { get; set; }
        public virtual U_SDG_ATTACHMENT U_SDG_ATTACHMENT2 { get; set; }
        public virtual U_SDG_ATTACHMENT_USER U_SDG_ATTACHMENT_USER { get; set; }
    }
}
