//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_SPECIAL_INSPECTION_USER
    {
        public long U_SPECIAL_INSPECTION_ID { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        public Nullable<long> U_OPERATOR { get; set; }
        public Nullable<decimal> U_ORDER { get; set; }
        public Nullable<decimal> U_ORDER_NUMBER { get; set; }
        public Nullable<long> U_ROLE { get; set; }
        public Nullable<long> U_SDG_ID { get; set; }
        public Nullable<long> U_SENDER_PATHOLOGIST { get; set; }
        public string U_TYPE { get; set; }
    
        public virtual LIMS_ROLE LIMS_ROLE { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual OPERATOR OPERATOR1 { get; set; }
        public virtual SDG SDG { get; set; }
        public virtual U_SPECIAL_INSPECTION U_SPECIAL_INSPECTION { get; set; }
    }
}
