//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_WRDESTINATION_USER
    {
        public long U_WRDESTINATION_ID { get; set; }
        public string U_COPIES { get; set; }
        public string U_DEVICE_NAME { get; set; }
        public string U_TYPE { get; set; }
        public Nullable<long> U_WREPORT_ID { get; set; }
        public string U_RECIPIENT_TYPE { get; set; }
    
        public virtual U_WRDESTINATION U_WRDESTINATION { get; set; }
        public virtual U_WREPORT U_WREPORT { get; set; }
    }
}
