//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_WREPORT
    {
        public U_WREPORT()
        {
            this.U_WREPORT1 = new HashSet<U_WREPORT>();
            this.U_WREPORT_QUERY_USER = new HashSet<U_WREPORT_QUERY_USER>();
            this.U_WRDESTINATION_USER = new HashSet<U_WRDESTINATION_USER>();
        }
    
        public long U_WREPORT_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual U_WREPORT_USER U_WREPORT_USER { get; set; }
        public virtual ICollection<U_WREPORT> U_WREPORT1 { get; set; }
        public virtual U_WREPORT U_WREPORT2 { get; set; }
        public virtual ICollection<U_WREPORT_QUERY_USER> U_WREPORT_QUERY_USER { get; set; }
        public virtual ICollection<U_WRDESTINATION_USER> U_WRDESTINATION_USER { get; set; }
    }
}
