//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_WRDESTINATION
    {
        public U_WRDESTINATION()
        {
            this.U_WRDESTINATION1 = new HashSet<U_WRDESTINATION>();
        }
    
        public long U_WRDESTINATION_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual U_WRDESTINATION_USER U_WRDESTINATION_USER { get; set; }
        public virtual ICollection<U_WRDESTINATION> U_WRDESTINATION1 { get; set; }
        public virtual U_WRDESTINATION U_WRDESTINATION2 { get; set; }
    }
}
