//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_WREPORT_USER
    {
        public long U_WREPORT_ID { get; set; }
        public string U_WORKFLOW_NAME { get; set; }
        public string U_WORKFLOW_EVENT { get; set; }
        public string U_WORD_TEMPLATE { get; set; }
        public string U_PARAM_PHRASE { get; set; }
        public string U_ENVELOPE_QUERY { get; set; }
    
        public virtual U_WREPORT U_WREPORT { get; set; }
    }
}
