//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDG_EXTRA_REQUEST
    {
        public long SDG_ID { get; set; }
        public string ADVISOROPERATOR { get; set; }
        public string REMARKSREQUESTS { get; set; }
    }
}
