//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDG_CASE_FLAGS
    {
        public long SDG_ID { get; set; }
        public string HAS_REMARKS { get; set; }
        public string HAS_SECOND_INSPECTION { get; set; }
        public string HAS_RESCAN { get; set; }
        public string HAS_FINISH_RESCAN { get; set; }
        public string HAS_EXTRA_MATERIAL { get; set; }
        public string HAS_FINISH_EXTRA_MATERIAL { get; set; }
        public string HAS_COLORS { get; set; }
        public string HAS_FINISH_COLORS { get; set; }
        public string HAS_FINISH_ADVISE { get; set; }
        public string IS_ADVISOR { get; set; }
        public string HAS_MULTIPLE { get; set; }
    }
}
