//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDG_SCAN_ATTACHMENT
    {
        public long SDG_ID { get; set; }
        public string HAS_SLIDES_SCANED { get; set; }
        public Nullable<System.DateTime> SCANNED_ON { get; set; }
        public Nullable<decimal> UNSCANNED_SLIDES_NUMBER { get; set; }
        public string HAS_ATTACHED_DOCS { get; set; }
    }
}
