//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDG_SAMPLE_ALIQUOT
    {
        public long SDG_ID { get; set; }
        public Nullable<decimal> NUM_OF_BLOCKS { get; set; }
        public Nullable<decimal> NUM_OF_COLORS { get; set; }
        public string COLORS { get; set; }
        public Nullable<decimal> EMPTY_BLOCKS_NUMBER { get; set; }
        public Nullable<decimal> U_GLASS_TYPE { get; set; }
    }
}
