//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SDG_MAIN_INFO
    {
        public long SDG_ID { get; set; }
        public string SDGNAME { get; set; }
        public string SDGSTATUS { get; set; }
        public Nullable<decimal> U_PRIORITY { get; set; }
        public string PRIO_TXT { get; set; }
        public Nullable<System.DateTime> U_SEND_ON { get; set; }
        public Nullable<long> U_PATHOLOG { get; set; }
        public string U_PATHOLAB_NUMBER { get; set; }
        public string REVISION { get; set; }
        public Nullable<decimal> U_WEEK_NBR { get; set; }
        public string U_PDF_PATH { get; set; }
        public string PATHOLOG_FULL_NAME { get; set; }
        public string PATHOLOG_NAME { get; set; }
        public string IS_DIGITAL { get; set; }
    }
}
