//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTANA
    {
        public long U_EXTRA_REQUEST_DATA_ID { get; set; }
        public long U_EXTRA_REQUEST_ID { get; set; }
        public string U_SLIDE_NAME { get; set; }
        public string PATIENT_ID { get; set; }
        public string PATIENT_FIRST_NAME { get; set; }
        public string PATIENT_LAST_NAME { get; set; }
        public Nullable<System.DateTime> U_DATE_OF_BIRTH { get; set; }
        public string U_GENDER { get; set; }
        public string U_HEBREW_NAME { get; set; }
        public Nullable<long> U_CREATED_BY { get; set; }
        public string INTERNAL_SLIDE { get; set; }
        public string SAMPLE { get; set; }
        public string BLOCK { get; set; }
        public Nullable<System.DateTime> U_CREATED_ON { get; set; }
        public string U_PROTOCOL_NAME { get; set; }
        public Nullable<decimal> U_PROTOCOL_NUMBER { get; set; }
        public string U_REQUEST_DETAILS { get; set; }
        public string U_STAIN { get; set; }
        public string U_STATUS { get; set; }
    }
}
