//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_NODE
    {
        public WORKFLOW_NODE()
        {
            this.ALIQUOTs = new HashSet<ALIQUOT>();
            this.RESULTs = new HashSet<RESULT>();
            this.SAMPLEs = new HashSet<SAMPLE>();
            this.SDGs = new HashSet<SDG>();
            this.TESTs = new HashSet<TEST>();
            this.U_CONTAINER = new HashSet<U_CONTAINER>();
            this.U_ORDER = new HashSet<U_ORDER>();
            this.CHILD_NODEs = new HashSet<WORKFLOW_NODE>();
        }
    
        public long WORKFLOW_NODE_ID { get; set; }
        public Nullable<long> WORKFLOW_ID { get; set; }
        public Nullable<long> WORKFLOW_NODE_TYPE_ID { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public string NAME { get; set; }
        public string EXTRA { get; set; }
        public string EVENTS { get; set; }
        public string USAGE { get; set; }
        public string WORKFLOW_PROMPT_TYPE { get; set; }
        public string WORKFLOW_PROMPT_COLUMN { get; set; }
        public Nullable<long> WORKFLOW_LEVEL { get; set; }
        public Nullable<int> TEMPLATE { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public string LONG_NAME { get; set; }
        public string PARAMETER_1 { get; set; }
        public string PARAMETER_2 { get; set; }
        public string PARAMETER_3 { get; set; }
        public string PARAMETER_4 { get; set; }
        public string PARAMETER_5 { get; set; }
    
        public virtual ICollection<ALIQUOT> ALIQUOTs { get; set; }
        public virtual ICollection<RESULT> RESULTs { get; set; }
        public virtual ICollection<SAMPLE> SAMPLEs { get; set; }
        public virtual ICollection<SDG> SDGs { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
        public virtual ICollection<U_CONTAINER> U_CONTAINER { get; set; }
        public virtual ICollection<U_ORDER> U_ORDER { get; set; }
        public virtual WORKFLOW WORKFLOW { get; set; }
        public virtual ICollection<WORKFLOW_NODE> CHILD_NODEs { get; set; }
        public virtual WORKFLOW_NODE PARENT_NODE { get; set; }
    }
}
