//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSTATION
    {
        public WORKSTATION()
        {
            this.ALIQUOT_USER = new HashSet<ALIQUOT_USER>();
            this.ALIQUOT_USER1 = new HashSet<ALIQUOT_USER>();
            this.WORKSTATION1 = new HashSet<WORKSTATION>();
        }
    
        public long WORKSTATION_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION_STATUS { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string WORKSTATION_TYPE { get; set; }
        public string ALLOW_USER_LOGIN { get; set; }
        public string ALLOW_BACKGROUND { get; set; }
        public string ALLOW_INSTRUMENTS { get; set; }
        public Nullable<long> LOCATION_ID { get; set; }
        public Nullable<long> WORKSTATION_GROUP_ID { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
        public Nullable<long> DESTINATION_ID { get; set; }
        public string AUTO_EXIT { get; set; }
        public Nullable<int> INACTIVITY_TIMER { get; set; }
        public Nullable<int> MAX_RETRIES { get; set; }
        public string SECURITY_SERVER { get; set; }
        public string NAMING_CONTEXT { get; set; }
        public string BACKGROUND_INSTRUMENTS { get; set; }
        public string FREEZE_ON_LOCKOUT { get; set; }
        public string AUTO_OPERATOR { get; set; }
        public Nullable<long> DEFAULT_OPERATOR_ID { get; set; }
    
        public virtual ICollection<ALIQUOT_USER> ALIQUOT_USER { get; set; }
        public virtual ICollection<ALIQUOT_USER> ALIQUOT_USER1 { get; set; }
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual OPERATOR OPERATOR { get; set; }
        public virtual ICollection<WORKSTATION> WORKSTATION1 { get; set; }
        public virtual WORKSTATION WORKSTATION2 { get; set; }
        public virtual WORKSTATION_USER WORKSTATION_USER { get; set; }
    }
}
