//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW
    {
        public WORKFLOW()
        {
            this.U_PARTS_USER = new HashSet<U_PARTS_USER>();
            this.U_PARTS_USER1 = new HashSet<U_PARTS_USER>();
            this.WORKFLOW_NODE = new HashSet<WORKFLOW_NODE>();
            this.WORKFLOW1 = new HashSet<WORKFLOW>();
            this.U_PARTS_USER11 = new HashSet<U_PARTS_USER>();
        }
    
        public long WORKFLOW_ID { get; set; }
        public Nullable<long> WORKFLOW_NODE_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string VERSION_STATUS { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public string CLASSIFICATION { get; set; }
        public Nullable<long> PARENT_VERSION_ID { get; set; }
        public string ENABLE_DISPLAY { get; set; }
    
        public virtual LIMS_GROUP LIMS_GROUP { get; set; }
        public virtual ICollection<U_PARTS_USER> U_PARTS_USER { get; set; }
        public virtual ICollection<U_PARTS_USER> U_PARTS_USER1 { get; set; }
        public virtual ICollection<WORKFLOW_NODE> WORKFLOW_NODE { get; set; }
        public virtual ICollection<WORKFLOW> WORKFLOW1 { get; set; }
        public virtual WORKFLOW WORKFLOW2 { get; set; }
        public virtual WORKFLOW_USER WORKFLOW_USER { get; set; }
        public virtual ICollection<U_PARTS_USER> U_PARTS_USER11 { get; set; }
    }
}
