//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patholab_DAL_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSTATION_USER
    {
        public long WORKSTATION_ID { get; set; }
        public string U_PRINTER_NAME { get; set; }
    
        public virtual WORKSTATION WORKSTATION { get; set; }
    }
}
